{
 "title": "odroid",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "static_iaq",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"static_iaq\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "pressure",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"pressure\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "iaq",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"iaq\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "gas",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"gas\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "bsec_status",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"bsec_status\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "raw_temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"raw_temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "raw_humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"raw_humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "iaq_accuracy",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"iaq_accuracy\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "co2_equivalent",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"co2_equivalent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "breath_voc_equivalent",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"breath_voc_equivalent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "BME680",
   "type": "timeseries",
   "description": "BOSH BME680 sensor",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"IoT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"breath_voc_equivalent\" or r[\"topic\"] == \"bsec_status\" or r[\"topic\"] == \"co2_equivalent\" or r[\"topic\"] == \"gas\" or r[\"topic\"] == \"humidity\" or r[\"topic\"] == \"iaq\" or r[\"topic\"] == \"iaq_accuracy\" or r[\"topic\"] == \"pressure\" or r[\"topic\"] == \"raw_humidity\" or r[\"topic\"] == \"raw_temperature\" or r[\"topic\"] == \"static_iaq\" or r[\"topic\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}